name: networking_test
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.4.2
  json_annotation: any
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  dio: ^5.8.0

  flutter_html: any
  shared_preferences: any
  image_picker: any
  cached_network_image: ^3.3.0
  provider: any
  flutter_spinkit: any
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  flutter_lints: ^5.0.0
  json_serializable: any
  build_runner: any

flutter:


  uses-material-design: true
